fofix/fofix

- README.md
The new activity made me curious. After pulling the new code I noticed the game wouldn't run as a dependency was missing.
This simple addition to the README.md only covers the case of GNU/Linux users but is a step in the right direction.
(I would have pushed it myself but it seems I am not (and never was?) a member of the project on GitHub).
> Adds info about new dependency on cerializer.

- FoFiX.py
Issues:
- fullscreen is reset to False on relaunch fofix
add default=None to args parser
> Fix fullscreen config reset on relaunch fofix

- README.md
The win32 dep pack is still available in the googlecode archive.
Fix #75
> README: use the googlecode archive link for the win32 pack

- README.md
- doc/source/quickstart/installation.rst
The `cerealizer` package should be installed manually, due to a bug in its setup.
> Doc: add a patch to install the `cerealizer` package

- requirements.txt
This will remove the mercurial dependency and will not use an old repo.
> Requirements: get pygame from PyPI

- FoFiX.py
Recent commit collected imports at the top, which breaks the startup process.
Commit was: bb5658c0fee5abec146f16a8a653d568dd1793f8 "Clean up the launcher (pep8)"
> Repair damage to import order

- fofix/core/Language.py
Futurize `fofix.core.Language` as a small step toward #110.
Also replace `fretwork.unicodify` with `gettext.NullTranslations` as converting to Python 3 will otherwise remove the need for `unicodify` and `NullTranslations` is intended as the "dummy" `_`.
> Futurize fofix.core.Language

- .gitignore
- doc/source/conf.py
This folder does not exists.
Ignore the build dir too.
> Doc: comment the HTML static path as it does not exists

- doc/source/quickstart/installation.rst
- requirements.txt
This version fixes its installation bugs: it is not necessary to install it in no-binary mode anymore.
Remove the note about Cerealizer in the installation doc.
> Update the Cerealizer dependency to 0.8.2

- setup.py
When compiling on mac with xcode 10 the standard library headers are not found.
This adds an extra compile and link option to find them.
Second attempt, this one passes gitlint.
fixes #187
> Fix locating stdlib on macos

- .travis.yml
Even though Trusty is EOL, it is still useful for tests requiring OpenGL.
This is the first step in the migration to Xenial.
Ref #193
> Travis: use Trusty as default

- setup.py
Fixes https://github.com/fofix/fofix/issues/196
> Use platform.uname() instead of os.uname()

- fofix/game/guitarscene/instruments/Vocalist.py
The name of the module conflict with the name of one of its method.
This is a hot fix for #199, not the right solution.
> Vocalist: import random instead of random.random

- FoFiX.py
The variable was renamed after a merge, and was not the right one.
> Launcher: fix the name of the args variable

- FoFiX.py
- README.md
- doc/source/quickstart/installation.rst
- fofix/core/Language.py
- makefile
The user needs to compile translations before launching the game.
Adding some doc about that, plus some minor fixes, should solve the issue #205.
By the way, a small cleaning of the launcher allows to have more logs for startup errors.
> Compile translations before launching the game

- fofix/core/GameEngine.py
Image.VERSION always reports 1.1.7, it is deprecated since version
5.2.0 (see https://github.com/python-pillow/Pillow/pull/3090), and
removed from version 6.0.0. The recommended way to access the version
of Pillow is `Image.__version__`.
> Use Pillow version number

- fofix/core/Theme.py
Fix for this error trying to play any songs or using preview:
```
Traceback (most recent call last):
File "FoFiX.py", line 171, in <module>
main.run()
File "/opt/fofix-git/fofix/game/Main.py", line 131, in run
while self.engine.run():
File "/opt/fofix-git/fofix/core/GameEngine.py", line 649, in run
rtn = self.mainloop()
File "/opt/fofix-git/fofix/core/GameEngine.py", line 633, in main
self.view.render()
File "/opt/fofix-git/fofix/core/View.py", line 263, in render
layer.render(self.visibility[layer], layer == self.layers[-1])
File "/opt/fofix-git/fofix/game/Lobby.py", line 457, in render
self.engine.theme.themeLobby.renderPanels(self)
File "/opt/fofix-git/fofix/core/Theme.py", line 871, in renderPanels
lobby.fontDict[self.theme.lobbyTitleTextFont].render(self.theme.lobbyTitleText, …
```
> fix lobbyTitleTextPos to be properly cast as float

- FoFiX.py
- requirements.txt
This `fretwork` update let us update other requirements (NumPy, Pygame, PyOpenGL).
This update other dependencies to their latest version before Python 3 / SDL 2 (december update):
- Cerealizer
- Cython
- NumPy
- olefile
- PyOpenGL.
> Dependency: bump fretwork to 0.5.0 and other deps

- fofix/core/Config.py
- fofix/tests/core/test_config.py
If the section value contains non ascii characters like "ö", then the string needs to be encoded to utf8 before writing it into a config file like `fofix.ini`.
This PR adds a test for this case and clean up the code of the module.
This PR should fix #209 (with #189).
> fix(config): encode the section value to utf-8

- .github/workflows/tests.yml
Python 3 tests are not required for CI to pass.
All maintained python versions are tested: 3.6, 3.7, 3.8 and 3.9.
> ci(python3): run optional tests and fail fast

- fofix/core/ConfigDefs.py
- fofix/core/Font.py
- fofix/core/Player.py
- fofix/game/song/song.py
To be compatible with Python 3, comparisons and sorts are reviewed :
- the `__cmp__` method is replaced with richer comparing methods, plus the `@functools.total_ordering` decorator
- the `cmp` function is removed (and not needed anymore)
- the `cmp` argument of `sort` and `sorted` is replaced with the `key` argument.
Some functions and methods are also reviewed to make the code working : 
- `fofix.core.ConfigDefs.sortOptionsByKey`: the `keys` dict. method is not adapted and is replaced with the `items` dict. method
- `fofix.game.song.song`: the `compareSongsAndTitles` function is removed because sorting is stable (https://docs.python.org/3/howto/sorting.html#sort-stability-and-complex-sorts) and already done when gettings songs info.
Ref:
- #110 
- …
> fix(cmp): use Python 3 syntax to compare and sort data

- fofix/core/Data.py
- fofix/core/Player.py
- fofix/core/Theme.py
- fofix/game/guitarscene/GuitarScene.py
> fix(python3): replace xrange with range

- fofix/game/Credits.py
Those languages are not available anymore:
- French (reform 1990)
- Pig Latin
- Portuguese (Brazilian)
- Russian
- Swedish.
Ref #127
> refactor(translations): remove not available langs

- data/themes/MegaLight/CustomTheme.py
- fofix/core/Config.py
- fofix/core/Data.py
- fofix/core/Image.py
- fofix/core/Resource.py
- fofix/core/Theme.py
- fofix/core/Version.py
- fofix/core/utils.py
- fofix/game/Dialogs.py
- fofix/game/GameResultsScene.py
- fofix/game/Menu.py
- fofix/game/song/song.py
- fofix/tests/core/test_config.py
- fofix/tests/core/test_resource.py
- fofix/tests/core/test_utils.py
- requirements.txt
The game is using `six` to keep python2 compatibility during the migration.
Plus, `fretwork.unicode.utf8` and `fretwork.unicode.unicodify` functions are not python3 compatible with fretwork v0.5. Then they are adapted with `six` and marked as deprecated.
Ref #110
> feat: use six

- data/themes/MegaLight V4/CustomRMLayers.py
- fofix/core/Config.py
- fofix/core/GameEngine.py
- fofix/core/Image.py
- fofix/core/Language.py
- fofix/core/Player.py
- fofix/core/Shader.py
- fofix/core/Theme.py
- fofix/game/Dialogs.py
- fofix/game/MainMenu.py
- fofix/tests/core/test_config.py
- fofix/tests/core/test_resource.py
Some methods and objects need to be changed for python 2 - python 3 compatibility:
- `print` needs parentheses
- `str` native methods can be used instead of old `string` methods
- `IOBase` should replace `file` keyword
- `gettext` should replace `ugettext`
- `string.letters` should be replaced with `string.ascii_letters`
- convert bytes to string and vice versa
- use `traceback` to get all exception
- handle the `None` side case in instrument types.
Ref #110
> fix(py3): use python3 compat' methods and objects

- fofix/core/Player.py
`Controls.checkMapping` does not use the `i` argument.
> refactor(player): remove an unused argument

- fofix/core/Settings.py
- fofix/game/Menu.py
- fofix/game/guitarscene/instruments/Guitar.py
- fofix/game/song/song.py
* In python 3, `values()` and `keys()` do not return lists anymore, so results should be converted to list to sort them later
* Int values should be initialized with an int value.
Ref #110
> fix(py3): use right types from py2

- fofix/core/Player.py
In the settings menu, some values are sorted. `None` value should be sortable. To do that, it is converted to a string.
> fix(controls): convert None to a string to sort it

- .github/workflows/tests.yml
The following actions are updated:
- actions/checkout: v2 → v3
- actions/setup-python: v2 → v4.
> ci: update github actions

- src/Audio.py
If PyOGG is not available, the StreamingOggSound class will not have been defined when constructing a new StreamingSound for an .ogg file.
This can result in logs similar to:
(W) Unable to load guitar track: global name 'StreamingOggSound' is not defined
> fix: 'StreamingOggSound' is not defined

- src/Audio.py
StreamingSound.streamIsPlaying() is currently implemented by returning Sound.get_num_channels(). This will result in an error since the Sound class has no method get_num_channels(). It does have a method isPlaying() which calls get_num_channels() on its self.sound object. Use this method instead.
> fix: AttributeError: type object 'Sound' has no attribute 'get_num_channels'
