fofix/fofix

- fofix/core/VideoPlayer/VideoPlayer.c
Well, that's enough to say ! Just changed the define names.
> support ffmpeg3.0

- README.md
- requirements.txt
> Clean up the README

- .gitignore
- fofix/core/Resource.py
- fofix/game/SongChoosingScene.py
Also switched SongChoosingScene to override render3D, as designed in Scene.py.
> Fix bugs to make song previewing work.

- .gitlint
- .travis.yml
- README.md
- fofix/tests/__init__.py
- fofix/tests/core/test_gameenginge.py
- fofix/tests/game/test_menu.py
The Travis CI service was added to repo settings.
> Use Travis to launch tests

- CONTRIBUTING.md
- doc/requirements.txt
- doc/source/conf.py
- doc/source/misc/contributing.rst
- doc/source/misc/index.rst
As a GPL-licensed software, contributions are welcomed. Then adding guidelines could be useful.
> Add contributing guidelines

- fofix/core/GameEngine.py
- fofix/core/Theme.py
- fofix/game/MainMenu.py
- fofix/game/SongChoosingScene.py
- fofix/game/guitarscene/instruments/Drum.py
Fix for #49 and related bugs. Also fixes where selection menu would quit before allowing access to base_library dir.
This pull is based off fofix/master!
> Fix #49 and related bugs

- .gitignore
Slashes added to ensure only the right things get ignored.
> Clean and document gitignore

- CREDITS
- fofix/game/Credits.py
Fix credit screen to actually display credits. There were a number of display bugs, plus the CREDITS file was not displayed.
> Fixup credit display, add myself.

- FoFiX.py
- fofix/core/GameEngine.py
- fofix/game/MainMenu.py
- fofix/game/SongChoosingScene.py
The oneshot mode is broken. The first thing to do is to remove it, while the code is not clean enough to re-implement it cleanly.
Ref #91
> Remove the oneshot mode

- FoFiX.py
- fofix/core/VFS.py
- fofix/core/Video.py
- fofix/game/song/song.py
- setup.py
Fix issue #69 (both parts). Also finish py2exe for win32.
Rebase of #87 to current fofix/master, plus better commits.
> Fix #69 (both parts)

- fofix/core/Theme.py
- fofix/game/Menu.py
- fofix/game/song/song.py
Fix a number of crashes experienced when running latest `master` on Linux with a custom theme.
> Fix stability issues

- fofix/game/SongChoosingScene.py
Press button 5 to exit without changing directory.
> Add a way to exit without changing directory

- CREDITS
- fofix/game/Credits.py
Add some contributors to CREDITS.
Flake8 the Credits module.
> Add some contributors to CREDITS + flake8

- fofix/game/guitarscene/instruments/Vocalist.py
> Fix compile error

- README.md
- doc/source/quickstart/quickstart.rst
- doc/source/users/songs.rst
- doc/source/users/themes.rst
- fofix/core/GameEngine.py
- fofix/game/Credits.py
The forum has changed its domain extension.
See https://www.fretsonfire.org/forums/viewtopic.php?f=26&t=60883 for more information.
> Change URLs of the forum fretsonfire.org

- setup.py
This will fix subprocess errors in python 3.
Ref #110
> Convert subprocess bytes to str

- setup.py
> Translations: fix setup commands

- fofix/core/Data.py
- Add some docstrings
- remove names in comments
- clean up some variables.
> Clean up the Data module

- fofix/core/Font.py
- fofix/core/Theme.py
* Add some docstrings
* use the utf-8 encoding for the module
* remove unused methods (``Font.loadCache`` and ``Font.setCustomGlyph``)
* remove the unused ``Font.render`` ``new`` argument.
> Clean up the Font module

- fofix/game/guitarscene/instruments/Instrument.py
- Fix a typo (which was a syntax error)
- remove comparisons to a booleam and to `None`
- add some docstrings
- remove names in comments
- clean up some variables.
> Clean up the Instrument module

- fofix/core/Image.py
Clean up docstrings, spaces and comments. Use the utf-8 encoding for the module too.
> Clean up the Image module

- fofix/game/Dialogs.py
Clean up docstrings, spaces and comments.
Replace lists as default params with `None`.
Simplify the for loop to select a neck.
> Clean up the Dialogs module

- doc/source/misc/releasenotes.rst
- fofix/core/ConfigDefs.py
- fofix/game/GameResultsScene.py
Rename the option *uploadurl_w67_starpower* to *uploadurl* in ``fofix.ini``.
> Rename the uploadurl option in fofix.ini

- fofix/game/guitarscene/instruments/Drum.py
> Use the right section for 'log_class_inits'

- fofix/core/Data.py
- fofix/core/GameEngine.py
- fofix/core/Input.py
- fofix/core/Language.py
- fofix/core/Microphone.py
- fofix/core/Mod.py
- fofix/core/Shader.py
- fofix/core/Texture.py
- fofix/core/Theme.py
- fofix/core/Video.py
- fofix/game/Credits.py
- fofix/game/GameResultsScene.py
- fofix/game/MainMenu.py
- fofix/game/Menu.py
- fofix/game/guitarscene/GuitarScene.py
- fofix/game/guitarscene/Stage.py
- fofix/game/song/song.py
The `logging.warn` method is deprecated in python 3.
Ref #110
> Use logging.warning instead of logging.warn

- fofix/game/Menu.py
Clean up spaces and comments. Add docstrings.
Deprecate the `unicode` argument of the `Menu.keyPressed` method.
> Cleanup the Menu module

- fofix/game/MainMenu.py
Clean up spaces and remove names in comments.
Add docstrings.
Deprecate the `newSinglePlayerGame` method as it is not used anymore.
> Clean up the MainMenu module

- FoFiX.py
- requirements.txt
Use the version 0.4.0.
Fix #104.
> Bump the version of fretwork

- fofix/core/Theme.py
Clean up spaces, remove names in comments and sort imports.
Replace 'type' vars.
Make some translations easier.
> Clean up the Theme module

- fofix/game/guitarscene/instruments/Vocalist.py
Clean up spaces.
Remove names in comments.
Sort imports.
> Vocalist: clean up the module

- fofix/game/guitarscene/Rockmeter.py
- Complete docstrings
- sort imports
- remove some local vars
- comparison with None
- clean up spaces
- clean up imports
- simplify code
- initialize vars.
> Clean up the Rockmeter module

- fofix/core/Scene.py
- fofix/tests/core/test_scene.py
Init tests for the `core.Scene` module, and sort imports for this module.
> Tests: init tests for the core.Scene module

- data/themes/MegaLight V4/theme.ini
This fully-specified file makes a good starting point for future theme developers.
> Copy all defaults and docs from Theme.py

- fofix/core/Mesh.py
- fofix/tests/core/test_mesh.py
Add some tests and docstrings for the `core.Mesh` module.
> Tests: init tests for the core.Mesh module

- README.md
The landscape.io website is down.
> doc(readme): remove the landscape badge

- fofix/game/song/song.py
- Add inheritance to `object` for old style class
- clean up spaces
- complete some docstrings
- escape Python or reserved keywords (`hash`, `tuple`, `time`)
- remove pseudo in comments
- remove useless brackets
- use a better syntax for `not in`
- use raw strings for regex.
> chore(song): clean up the game module

- fofix/core/Config.py
having song titles with non ascii charackters inside a `song.ini` crashes FoFix
> fix non ascii song titles

- fofix/core/Resource.py
- fofix/tests/core/test_resource.py
Exceptions are raised in a future-proof way.
> chore(resource): clean up the code and add tests

- fofix/core/SceneFactory.py
To clean up the module:
- add docstrings
- use upper snake case.
> chore(scenefactory): clean up the module

- fofix/tests/core/test_font.py
Init tests for the module `fofix.core.Font`.
> test(font): test `Cache` and `Font` classes

- .gitignore
For more information: https://fr.wikipedia.org/wiki/.DS_Store.
> chore(git): ignore .DS_Store files

- fofix/game/song/song.py
`Part` and `Difficulty` objects need type checking before comparing objects.
> fix(song): check the type of class before sorting

- fofix/core/Shader.py
- fofix/game/Dialogs.py
- fofix/game/Scorekeeper.py
- fofix/game/SongChoosingScene.py
- fofix/game/guitarscene/instruments/Drum.py
- fofix/game/guitarscene/instruments/Guitar.py
- In Python 3, `/` is float division
- In Python 2, `/` is integer division (assuming `int` inputs)
- In both 2 and 3, `//` is integer division.
> fix(python3): get integers after some divisions

- fofix/core/Data.py
- fofix/core/Input.py
- fofix/core/Player.py
- fofix/core/Settings.py
- fofix/game/Dialogs.py
- fofix/game/GameResultsScene.py
- fofix/game/MainMenu.py
- fofix/game/Menu.py
- fofix/game/Scorekeeper.py
- fofix/game/guitarscene/instruments/Drum.py
- fofix/game/guitarscene/instruments/Guitar.py
- fofix/game/song/song.py
This config parameters is not needed : all init logs are welcomed :).
> refactor(config): remove game/log_class_inits

- src/Video.py
> fix(pillow): use Image.tobytes instead of deprecated tostring

- fofix/core/Data.py
- fofix/core/GameEngine.py
- fofix/core/Player.py
- fofix/core/Theme.py
- fofix/game/MainMenu.py
- fofix/game/guitarscene/GuitarScene.py
- fofix/game/guitarscene/instruments/Instrument.py
- fofix/game/song/song.py
Some issues were logged with a low level.
> refactor(logs): use better levels for issues

- fofix/game/guitarscene/__init__.py
- fofix/game/guitarscene/instruments/Drum.py
- fofix/game/guitarscene/instruments/Guitar.py
- fofix/game/guitarscene/instruments/Instrument.py
- fofix/game/guitarscene/instruments/Vocalist.py
> refactor(instrus): clean up

- fofix/core/Config.py
- fofix/game/song/song.py
- fofix/tests/core/test_config.py
> fix(config): only write strings to the config file
